#!/usr/bin/env python3
"""
img2font.py — Convert a font image into a C header for UpOS.

Conversion rule:
    light pixel -> 1
    dark  pixel -> 0

The character grid is read left-to-right, top-to-bottom.
Each character is exactly `char_width` x `char_height` pixels.
"""

from pathlib import Path
from PIL import Image


# ============================================================
#  Internal helpers
# ============================================================

def _pack_row(pixels, width):
    """
    Pack a row of pixels into bytes.
    Bit order: MSB first (leftmost pixel = bit 7).
    Returns a list of ints (0-255).
    """
    bytes_per_row = (width + 7) // 8
    row = [0] * bytes_per_row

    for x in range(width):
        bit = 1 if pixels[x] else 0
        byte_index = x // 8
        bit_index  = 7 - (x % 8)
        row[byte_index] |= (bit << bit_index)

    return row


def _sanitize_identifier(name):
    """Return a valid C identifier from a name."""
    return "".join(c if c.isalnum() else "_" for c in name).lower()


def _format_hex(data, per_line=16, indent="    "):
    """Format a list of bytes as a C array body."""
    parts = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        parts.append(indent + ", ".join(f"0x{b:02X}" for b in chunk))
    return ",\n".join(parts)


# ============================================================
#  Main function
# ============================================================

def convert_image_to_font_h(name, author, image,
                            char_height, char_width,
                            char_count,
                            first_char, last_char,
                            flags, output,
                            threshold=128):
    """
    Convert a font image into a .h file containing a gfx_font_t.

    Parameters
    ----------
    name        : str  — font name (max 31 chars)
    author      : str  — author name (max 31 chars)
    image       : str  — input image path (.png/.bmp/.pgm/...)
    char_height : int  — character height in pixels
    char_width  : int  — character width in pixels
    char_count  : int  — number of characters in the image
    first_char  : int  — ASCII code of the first character (e.g. 32)
    last_char   : int  — ASCII code of the last character (e.g. 126)
    flags       : int  — font flags (0-255)
    output      : str  — output .h path
    threshold   : int  — light/dark threshold (0-255, default 128)

    Image layout
    ------------
    Characters must be laid out on a grid, filling rows
    left-to-right, top-to-bottom:

        [ A ][ B ][ C ][ D ]
        [ E ][ F ][ G ][ H ]
        ...

    Each cell is exactly `char_width` x `char_height` pixels.
    The total width must be a multiple of the cell width.
    """
    img = Image.open(image).convert("L")   # grayscale

    # Basic validations
    chars_per_row = img.width // char_width
    if chars_per_row == 0:
        raise ValueError(
            f"Image too narrow ({img.width}px) for "
            f"{char_width}px per character."
        )

    rows_needed = (char_count + chars_per_row - 1) // chars_per_row
    if img.height < rows_needed * char_height:
        raise ValueError(
            f"Image too small: requires "
            f"{rows_needed * char_height}px of height, "
            f"has {img.height}px."
        )

    if last_char - first_char + 1 != char_count:
        print(f"[warning] last - first + 1 = "
              f"{last_char - first_char + 1}, "
              f"but count = {char_count}.")

    # ---- Extract bits ----
    bytes_per_char_row = (char_width + 7) // 8
    data = []

    for idx in range(char_count):
        col = idx % chars_per_row
        row = idx // chars_per_row
        ox = col * char_width
        oy = row * char_height

        for y in range(char_height):
            row_pixels = []
            for x in range(char_width):
                px = img.getpixel((ox + x, oy + y))
                # light -> True (becomes bit 1)
                row_pixels.append(px >= threshold)
            data.extend(_pack_row(row_pixels, char_width))

    # ---- Generate the header ----
    identifier = _sanitize_identifier(name)
    guard = f"__{identifier.upper()}_H__"
    c_name  = name[:31]
    c_author = author[:31]
    bytes_per_char = bytes_per_char_row * char_height

    header = f"""/* ============================================================
 * Auto-generated by img2font.py — DO NOT edit manually.
 *
 * Font    : {c_name}
 * Author  : {c_author}
 * Size    : {char_width}x{char_height} px
 * Chars   : {char_count} ({first_char}..{last_char})
 * Bytes   : {len(data)} ({bytes_per_char} per character)
 * ============================================================ */
#ifndef {guard}
#define {guard}

#include <stdint.h>

typedef struct
{{
\tchar     name[32];
\tchar     author[32];
\tint      width;
\tint      height;
\tuint8_t *code;
\tint      charcount;
\tint      first_char;
\tint      last_char;
\tuint8_t  flags;
}} gfx_font_t;

static const uint8_t {identifier}_code[] = {{
{_format_hex(data)}
}};

gfx_font_t {identifier}_font = {{
\t.name       = "{c_name}",
\t.author     = "{c_author}",
\t.width      = {char_width},
\t.height     = {char_height},
\t.code       = (uint8_t *){identifier}_code,
\t.charcount  = {char_count},
\t.first_char = {first_char},
\t.last_char  = {last_char},
\t.flags      = {flags},
}};

#endif /* {guard} */
"""

    Path(output).write_text(header, encoding="utf-8")
    print(f"[OK] {output} generated.")
    print(f"     {char_count} characters "
          f"{char_width}x{char_height}px")
    print(f"     {len(data)} total bytes "
          f"({bytes_per_char} per character)")


# ============================================================
#  CLI
# ============================================================

def _cli():
    import argparse

    parser = argparse.ArgumentParser(
        description="Convert an image into a .h font for UpOS"
    )
    parser.add_argument("image", help="input image file")
    parser.add_argument("output", help="output .h file")
    parser.add_argument("-n", "--name", required=True,
                        help="font name")
    parser.add_argument("-a", "--author", default="Anonymous",
                        help="font author")
    parser.add_argument("-W", "--width", type=int, required=True,
                        help="character width in px")
    parser.add_argument("-H", "--height", type=int, required=True,
                        help="character height in px")
    parser.add_argument("-c", "--count", type=int, required=True,
                        help="number of characters in the image")
    parser.add_argument("--first", type=int, default=32,
                        help="first character code (default: 32, space)")
    parser.add_argument("--last", type=int, default=126,
                        help="last character code (default: 126, ~)")
    parser.add_argument("-f", "--flags", type=int, default=0)
    parser.add_argument("-t", "--threshold", type=int, default=128,
                        help="light/dark threshold 0-255 (default: 128)")

    args = parser.parse_args()

    convert_image_to_font_h(
        name=args.name,
        author=args.author,
        image=args.image,
        char_height=args.height,
        char_width=args.width,
        char_count=args.count,
        first_char=args.first,
        last_char=args.last,
        flags=args.flags,
        output=args.output,
        threshold=args.threshold,
    )


if __name__ == "__main__":
    _cli()