#!/usr/bin/env python3
"""
img2bmp.py — Convert an image into a C header with a gfx_bmp_t
bitmap for UpOS.

Conversion rule:
    light pixel -> 1
    dark  pixel -> 0

Each row is packed MSB-first (leftmost pixel = bit 7 of the first byte).
Rows are padded to a whole number of bytes.

Width and height are automatically detected from the image
if not explicitly provided.
"""

from pathlib import Path
from PIL import Image


# ============================================================
#  Internal helpers
# ============================================================

def _pack_row(pixels, width):
    """
    Pack a row of pixels into bytes.
    Bit order: MSB first (leftmost pixel = bit 7).
    Returns a list of ints (0-255).
    """
    bytes_per_row = (width + 7) // 8
    row = [0] * bytes_per_row

    for x in range(width):
        bit = 1 if pixels[x] else 0
        byte_index = x // 8
        bit_index  = 7 - (x % 8)
        row[byte_index] |= (bit << bit_index)

    return row


def _sanitize_identifier(name):
    """Return a valid C identifier from a name."""
    return "".join(c if c.isalnum() else "_" for c in name).lower()


def _format_hex(data, per_line=16, indent="    "):
    """Format a list of bytes as a C array body."""
    parts = []
    for i in range(0, len(data), per_line):
        chunk = data[i:i + per_line]
        parts.append(indent + ", ".join(f"0x{b:02X}" for b in chunk))
    return ",\n".join(parts)


# ============================================================
#  Main function
# ============================================================

def convert_image_to_bmp(name, image, output,
                         offset_x=0, offset_y=0,
                         width=None, height=None,
                         threshold=128):
    """
    Convert an image into a .h file containing a gfx_bmp_t.

    Parameters
    ----------
    name      : str  — bitmap name (max 31 chars)
    image     : str  — input image path
    output    : str  — output .h path
    offset_x  : int  — X offset inside the image (default: 0)
    offset_y  : int  — Y offset inside the image (default: 0)
    width     : int  — width in pixels. If None, uses the image width
                       minus offset_x.
    height    : int  — height in pixels. If None, uses the image height
                       minus offset_y.
    threshold : int  — light/dark threshold 0-255 (default: 128)
    """
    img = Image.open(image).convert("L")   # grayscale

    # ---- Auto-detect width/height ----
    if width is None:
        width = img.width - offset_x
    if height is None:
        height = img.height - offset_y

    # Bounds check
    if offset_x + width > img.width:
        raise ValueError(
            f"Region out of bounds: offset_x({offset_x}) + "
            f"width({width}) > image width({img.width})."
        )
    if offset_y + height > img.height:
        raise ValueError(
            f"Region out of bounds: offset_y({offset_y}) + "
            f"height({height}) > image height({img.height})."
        )

    # ---- Extract and pack ----
    bytes_per_row = (width + 7) // 8
    data = []

    for y in range(height):
        row_pixels = []
        for x in range(width):
            px = img.getpixel((offset_x + x, offset_y + y))
            # light -> True (becomes bit 1)
            row_pixels.append(px >= threshold)
        data.extend(_pack_row(row_pixels, width))

    # ---- Generate the header ----
    identifier = _sanitize_identifier(name)
    guard = f"__{identifier.upper()}_H__"
    c_name = name[:31]

    header = f"""/* ============================================================
 * Auto-generated by img2bmp.py — DO NOT edit manually.
 *
 * Bitmap  : {c_name}
 * Size    : {width}x{height} px
 * Bytes   : {len(data)} ({bytes_per_row} per row)
 * ============================================================ */
#ifndef {guard}
#define {guard}

#include <stdint.h>

typedef struct {{
\tchar     name[32];
\tint      width;
\tint      height;
\tuint8_t *data;
}} gfx_bmp_t;

static const uint8_t {identifier}_data[] = {{
{_format_hex(data)}
}};

gfx_bmp_t {identifier}_bmp = {{
\t.name   = "{c_name}",
\t.width  = {width},
\t.height = {height},
\t.data   = (uint8_t *){identifier}_data,
}};

#endif /* {guard} */
"""

    Path(output).write_text(header, encoding="utf-8")
    print(f"[OK] {output} generated.")
    print(f"     {width}x{height} px (auto-detected)")
    print(f"     {len(data)} total bytes ({bytes_per_row} per row)")


# ============================================================
#  CLI
# ============================================================

def _cli():
    import argparse

    parser = argparse.ArgumentParser(
        description="Convert an image into a .h bitmap for UpOS"
    )
    parser.add_argument("image", help="input image file")
    parser.add_argument("output", help="output .h file")
    parser.add_argument("-n", "--name", required=True,
                        help="bitmap name")
    parser.add_argument("-x", "--offset-x", type=int, default=0,
                        help="X offset inside the image (default: 0)")
    parser.add_argument("-y", "--offset-y", type=int, default=0,
                        help="Y offset inside the image (default: 0)")
    parser.add_argument("-W", "--width", type=int, default=None,
                        help="width in px (default: auto-detect)")
    parser.add_argument("-H", "--height", type=int, default=None,
                        help="height in px (default: auto-detect)")
    parser.add_argument("-t", "--threshold", type=int, default=128,
                        help="light/dark threshold 0-255 (default: 128)")

    args = parser.parse_args()

    convert_image_to_bmp(
        name=args.name,
        image=args.image,
        output=args.output,
        offset_x=args.offset_x,
        offset_y=args.offset_y,
        width=args.width,
        height=args.height,
        threshold=args.threshold,
    )


if __name__ == "__main__":
    _cli()